"""add sub-user role flow

Revision ID: 447a4e1de59d
Revises: 86f95e525db1
Create Date: 2026-05-21 14:35:48.210248

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
from sqlalchemy import text as _sa_text
import sqlalchemy as sa
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision: str = '447a4e1de59d'
down_revision: Union[str, None] = '86f95e525db1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sub_user_requests',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('principal_user_id', sa.Integer(), nullable=False),
    sa.Column('requested_full_name', sa.String(length=255), nullable=False),
    sa.Column('request_email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', name='sub_user_request_status'), nullable=False),
    sa.Column('processed_by_admin_id', sa.Integer(), nullable=True),
    sa.Column('request_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['principal_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['processed_by_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub_user_requests_principal_user_id'), 'sub_user_requests', ['principal_user_id'], unique=False)
    op.create_index(op.f('ix_sub_user_requests_status'), 'sub_user_requests', ['status'], unique=False)
    op.alter_column('audit_controls', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('audits', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('checklist_item_state', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('evidences', 'create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('messagens', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.add_column('users', sa.Column('full_name', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('parent_user_id', sa.Integer(), nullable=True))
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_index(op.f('ix_users_parent_user_id'), 'users', ['parent_user_id'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_foreign_key(None, 'users', 'users', ['parent_user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def _index_exists_fkguard(conn, index_name: str, table_name: str) -> bool:
    return (
        conn.execute(
            _sa_text(
                "SELECT COUNT(*) FROM information_schema.statistics "
                "WHERE table_schema = DATABASE() "
                "AND table_name = :tbl AND index_name = :idx"
            ),
            {"tbl": table_name, "idx": index_name},
        ).scalar()
        or 0
    ) > 0


def _index_backs_foreign_key(conn, index_name: str, table_name: str) -> bool:
    """True se alguma FOREIGN KEY desta tabela depende deste índice."""
    return (
        conn.execute(
            _sa_text(
                "SELECT COUNT(*) "
                "FROM information_schema.key_column_usage kcu "
                "JOIN information_schema.statistics s "
                "  ON s.table_schema = kcu.table_schema "
                " AND s.table_name   = kcu.table_name "
                " AND s.column_name  = kcu.column_name "
                "WHERE kcu.table_schema = DATABASE() "
                "  AND kcu.table_name = :tbl "
                "  AND kcu.referenced_table_name IS NOT NULL "
                "  AND s.index_name = :idx"
            ),
            {"tbl": table_name, "idx": index_name},
        ).scalar()
        or 0
    ) > 0


def _drop_index_if_safe(index_name: str, table_name: str) -> None:
    """
    Remove o índice só se ele existir e nenhuma FK depender dele.

    O MySQL recusa `DROP INDEX` sobre um índice que sustenta uma FOREIGN
    KEY:

        (1553, "Cannot drop index '...': needed in a foreign key
                constraint")

    Quando a tabela inteira é removida logo em seguida, ou quando a
    coluna é removida, o índice vai junto — não há o que fazer aqui.
    Descoberto na primeira execução real do job `migrations` do CI
    (2026-08-26): a suíte usa `Base.metadata.create_all` e o SQLite não
    impõe a mesma restrição, então nenhum teste local alcançava isto.
    """
    conn = op.get_bind()
    if not _index_exists_fkguard(conn, index_name, table_name):
        return
    if _index_backs_foreign_key(conn, index_name, table_name):
        return
    op.drop_index(index_name, table_name=table_name)


def _drop_foreign_key_on_column(table_name: str, column_name: str) -> None:
    """
    Remove a FOREIGN KEY que incide sobre `column_name`, qualquer que
    seja o nome dela.

    Nomes auto-atribuidos pelo MySQL (`<tabela>_ibfk_N`) dependem da
    ordem de criacao e variam entre bancos. Resolver pelo
    information_schema e a unica forma correta de escrever isto num
    downgrade que precisa rodar em qualquer instalacao.
    """
    conn = op.get_bind()
    nomes = [
        linha[0]
        for linha in conn.execute(
            _sa_text(
                "SELECT DISTINCT constraint_name "
                "FROM information_schema.key_column_usage "
                "WHERE table_schema = DATABASE() "
                "  AND table_name = :tbl "
                "  AND column_name = :col "
                "  AND referenced_table_name IS NOT NULL"
            ),
            {"tbl": table_name, "col": column_name},
        ).all()
    ]
    for nome in nomes:
        op.drop_constraint(nome, table_name, type_="foreignkey")


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    #
    # O autogenerate escreveu `op.drop_constraint(None, ...)` e ninguem
    # ajustou — o `None` fazia o Alembic estourar `AssertionError: name
    # is not None` e tornava esta migration IRREVERSIVEL desde 2026-05-21.
    # Passou dois meses despercebido porque nenhum teste executava
    # `alembic downgrade`; apareceu na primeira execucao real do job
    # `migrations` do CI (2026-08-26).
    #
    # O nome real da constraint e gerado pelo MySQL (`users_ibfk_1`), e
    # nao pode ser fixado no codigo: bancos criados em ordens diferentes
    # recebem numeracoes diferentes. Por isso e resolvido em tempo de
    # execucao, a partir do information_schema.
    _drop_foreign_key_on_column("users", "parent_user_id")
    _drop_index_if_safe("ix_users_role", "users")
    _drop_index_if_safe("ix_users_parent_user_id", "users")
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.drop_column('users', 'parent_user_id')
    op.drop_column('users', 'full_name')
    op.alter_column('messagens', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('evidences', 'create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('checklist_item_state', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('audits', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('audit_controls', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    _drop_index_if_safe("ix_sub_user_requests_status", "sub_user_requests")
    _drop_index_if_safe("ix_sub_user_requests_principal_user_id", "sub_user_requests")
    op.drop_table('sub_user_requests')
    # ### end Alembic commands ###

