"""create audit schema v1

Revision ID: 86f95e525db1
Revises: 
Create Date: 2026-04-28 17:44:46.962121

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
from sqlalchemy import text as _sa_text
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision: str = '86f95e525db1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'control_catalog',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('code', sa.String(length=50), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('expected_evidence', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_control_catalog_code'), 'control_catalog', ['code'], unique=True)
    
    op.create_table(
        'users',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('password_hash', sa.String(length=255), nullable=False),
        sa.Column('role', sa.String(length=32), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    
    op.create_table(
        'audits',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('client_user_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.Enum('DRAFT', 'ACTIVE', 'CLOSED', name='audit_status'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['client_user_id'], ['users.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_index(op.f('ix_audits_client_user_id'), 'audits', ['client_user_id'], unique=False)
    
    op.create_table(
        'checklist_items',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('control_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=False),
        sa.Column('sort_order', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['control_id'], ['control_catalog.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_index(op.f('ix_checklist_items_control_id'), 'checklist_items', ['control_id'], unique=False)
    
    op.create_table(
        'audit_controls',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('audit_id', sa.Integer(), nullable=False),
        sa.Column('control_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.Enum('EM_ANALISE', 'PARCIAL', 'CONFORME', name='audit_control_status'), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['audit_id'], ['audits.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['control_id'], ['control_catalog.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('audit_id', 'control_id', name='uq_audit_control_one_per_audit')
    )
    
    op.create_index(op.f('ix_audit_controls_audit_id'), 'audit_controls', ['audit_id'], unique=False)
    
    op.create_index(op.f('ix_audit_controls_control_id'), 'audit_controls', ['control_id'], unique=False)
    
    op.create_index(op.f('ix_audit_controls_status'), 'audit_controls', ['status'], unique=False)
    
    op.create_table(
        'checklist_item_state',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('audit_control_id', sa.Integer(), nullable=False),
        sa.Column('checklist_item_id', sa.Integer(), nullable=False),
        sa.Column('done', sa.Boolean(), nullable=False),
        sa.Column('done_at', sa.DateTime(timezone=True), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['audit_control_id'], ['audit_controls.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['checklist_item_id'], ['checklist_items.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('audit_control_id', 'checklist_item_id', name='uq_checklist_state_one_per_item_per_audit_control')
    )
    
    op.create_index(op.f('ix_checklist_item_state_audit_control_id'), 'checklist_item_state', ['audit_control_id'], unique=False)
    
    op.create_index(op.f('ix_checklist_item_state_checklist_item_id'), 'checklist_item_state', ['checklist_item_id'], unique=False)
    
    op.create_table(
        'evidences',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('audit_control_id', sa.Integer(), nullable=False),
        sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
        sa.Column('file_name', sa.String(length=255), nullable=False),
        sa.Column('storage_key', sa.String(length=500), nullable=False),
        sa.Column('mime_type', sa.String(length=100), nullable=True),
        sa.Column('size_bytes', sa.Integer(), nullable=True),
        sa.Column('create_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['audit_control_id'], ['audit_controls.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('storage_key')
    )
    
    op.create_index(op.f('ix_evidences_audit_control_id'), 'evidences', ['audit_control_id'], unique=False)
    
    op.create_index(op.f('ix_evidences_uploaded_by_id'), 'evidences', ['uploaded_by_id'], unique=False)
    
    op.create_table(
        'messagens',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('audit_control_id', sa.Integer(), nullable=False),
        sa.Column('author_user_id', sa.Integer(), nullable=False),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['audit_control_id'], ['audit_controls.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ondelete='RESTRICT'),
        sa.PrimaryKeyConstraint('id')
    )
    
    op.create_index(op.f('ix_messagens_audit_control_id'), 'messagens', ['audit_control_id'], unique=False)
    
    op.create_index(op.f('ix_messagens_author_user_id'), 'messagens', ['author_user_id'], unique=False)
    # ### end Alembic commands ###


def _index_exists_fkguard(conn, index_name: str, table_name: str) -> bool:
    return (
        conn.execute(
            _sa_text(
                "SELECT COUNT(*) FROM information_schema.statistics "
                "WHERE table_schema = DATABASE() "
                "AND table_name = :tbl AND index_name = :idx"
            ),
            {"tbl": table_name, "idx": index_name},
        ).scalar()
        or 0
    ) > 0


def _index_backs_foreign_key(conn, index_name: str, table_name: str) -> bool:
    """True se alguma FOREIGN KEY desta tabela depende deste índice."""
    return (
        conn.execute(
            _sa_text(
                "SELECT COUNT(*) "
                "FROM information_schema.key_column_usage kcu "
                "JOIN information_schema.statistics s "
                "  ON s.table_schema = kcu.table_schema "
                " AND s.table_name   = kcu.table_name "
                " AND s.column_name  = kcu.column_name "
                "WHERE kcu.table_schema = DATABASE() "
                "  AND kcu.table_name = :tbl "
                "  AND kcu.referenced_table_name IS NOT NULL "
                "  AND s.index_name = :idx"
            ),
            {"tbl": table_name, "idx": index_name},
        ).scalar()
        or 0
    ) > 0


def _drop_index_if_safe(index_name: str, table_name: str) -> None:
    """
    Remove o índice só se ele existir e nenhuma FK depender dele.

    O MySQL recusa `DROP INDEX` sobre um índice que sustenta uma FOREIGN
    KEY:

        (1553, "Cannot drop index '...': needed in a foreign key
                constraint")

    Quando a tabela inteira é removida logo em seguida, ou quando a
    coluna é removida, o índice vai junto — não há o que fazer aqui.
    Descoberto na primeira execução real do job `migrations` do CI
    (2026-08-26): a suíte usa `Base.metadata.create_all` e o SQLite não
    impõe a mesma restrição, então nenhum teste local alcançava isto.
    """
    conn = op.get_bind()
    if not _index_exists_fkguard(conn, index_name, table_name):
        return
    if _index_backs_foreign_key(conn, index_name, table_name):
        return
    op.drop_index(index_name, table_name=table_name)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    _drop_index_if_safe("ix_messagens_author_user_id", "messagens")
    
    _drop_index_if_safe("ix_messagens_audit_control_id", "messagens")
    
    op.drop_table('messagens')
    
    _drop_index_if_safe("ix_evidences_uploaded_by_id", "evidences")
    
    _drop_index_if_safe("ix_evidences_audit_control_id", "evidences")
    
    op.drop_table('evidences')
    
    _drop_index_if_safe("ix_checklist_item_state_checklist_item_id", "checklist_item_state")
    
    _drop_index_if_safe("ix_checklist_item_state_audit_control_id", "checklist_item_state")
    
    op.drop_table('checklist_item_state')
    
    _drop_index_if_safe("ix_audit_controls_status", "audit_controls")
    
    _drop_index_if_safe("ix_audit_controls_control_id", "audit_controls")
    
    _drop_index_if_safe("ix_audit_controls_audit_id", "audit_controls")
    
    op.drop_table('audit_controls')
    
    _drop_index_if_safe("ix_checklist_items_control_id", "checklist_items")
    
    op.drop_table('checklist_items')
    
    _drop_index_if_safe("ix_audits_client_user_id", "audits")
    
    op.drop_table('audits')
    
    _drop_index_if_safe("ix_users_email", "users")
    
    op.drop_table('users')
    
    _drop_index_if_safe("ix_control_catalog_code", "control_catalog")
    
    op.drop_table('control_catalog')
    # ### end Alembic commands ###

