"""add sub-user role flow

Revision ID: d60f999c1fca
Revises: 9d5a3c1b2e77
Create Date: 2026-05-22 17:19:14.122165

"""

from __future__ import annotations

from typing import Sequence, Union

from alembic import op
from sqlalchemy import text as _sa_text
import sqlalchemy as sa
from sqlalchemy import inspect as sa_inspect
from sqlalchemy.dialects import mysql


# revision identifiers, used by Alembic.
revision: str = 'd60f999c1fca'
down_revision: Union[str, None] = '9d5a3c1b2e77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_controls', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('audits', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('checklist_item_state', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('companies', 'phone',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=160),
               nullable=False)
    op.alter_column('companies', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index(op.f('uq_companies_email'), table_name='companies')
    op.drop_index(op.f('uq_companies_name'), table_name='companies')
    op.drop_index(op.f('uq_companies_principal_user_id'), table_name='companies')
    op.drop_index(op.f('ix_companies_email'), table_name='companies')
    op.create_index(op.f('ix_companies_email'), 'companies', ['email'], unique=True)
    op.drop_index(op.f('ix_companies_name'), table_name='companies')
    op.create_index(op.f('ix_companies_name'), 'companies', ['name'], unique=True)
    op.drop_constraint('companies_ibfk_1', 'companies', type_='foreignkey')
    op.drop_index(op.f('ix_companies_principal_user_id'), table_name='companies')
    op.create_index(op.f('ix_companies_principal_user_id'), 'companies', ['principal_user_id'], unique=True)
    op.create_foreign_key(
        None, 'companies', 'users',
        ['principal_user_id'], ['id'],
        ondelete='RESTRICT'
    )
    op.create_index(op.f('ix_companies_phone'), 'companies', ['phone'], unique=False)
    op.add_column('dashboard_card_checklist_items', sa.Column('iid', sa.Integer(), autoincrement=True, nullable=False))
    op.alter_column('dashboard_card_checklist_items', 'done',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('dashboard_card_checklist_items', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_column('dashboard_card_checklist_items', 'id')
    op.alter_column('dashboard_card_history_entries', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    bind = op.get_bind()
    fks = sa_inspect(bind).get_foreign_keys('dashboard_card_history_entries')
    fk_actor = next((f['name'] for f in fks if 'actor_user_id' in f.get('constrained_columns', [])), None)
    if fk_actor:
        op.drop_constraint(fk_actor, 'dashboard_card_history_entries', type_='foreignkey')
    op.drop_index(op.f('ix_dashboard_card_history_entries_actor_user_id'), table_name='dashboard_card_history_entries')
    if fk_actor:
        op.create_foreign_key(None, 'dashboard_card_history_entries', 'users', ['actor_user_id'], ['id'], ondelete='SET NULL')
    op.alter_column('dashboard_card_messages', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    bind = op.get_bind()
    fks = sa_inspect(bind).get_foreign_keys('dashboard_card_messages')
    fk_author = next((f['name'] for f in fks if 'author_user_id' in f.get('constrained_columns', [])), None)
    if fk_author:
        op.drop_constraint(fk_author, 'dashboard_card_messages', type_='foreignkey')
    op.drop_index(op.f('ix_dashboard_card_messages_author_user_id'), table_name='dashboard_card_messages')
    if fk_author:
        op.create_foreign_key(None, 'dashboard_card_messages', 'users', ['author_user_id'], ['id'], ondelete='RESTRICT')
    op.drop_index(op.f('ix_dashboard_card_messages_message_type'), table_name='dashboard_card_messages')
    op.alter_column('dashboard_card_notes', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.add_column('dashboard_cards', sa.Column('control_code', sa.String(length=40), nullable=False))
    op.add_column('dashboard_cards', sa.Column('status', sa.Enum('EM_ANALISE', 'PARCIAL', 'CONFORME', 'NAOCONFORME', name='dashboard_card_status'), nullable=False))
    op.alter_column('dashboard_cards', 'sort_order',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('dashboard_cards', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.create_index(op.f('ix_dashboard_cards_control_code'), 'dashboard_cards', ['control_code'], unique=False)
    op.create_index(op.f('ix_dashboard_cards_status'), 'dashboard_cards', ['status'], unique=False)
    op.alter_column('dashboard_template_cards', 'sort_order',
               existing_type=mysql.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('ix_dashboard_template_cards_tag'), table_name='dashboard_template_cards')
    op.alter_column('dashboard_templates', 'is_default',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=None,
               existing_nullable=False)
    op.alter_column('dashboard_templates', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.drop_index(op.f('ix_dashboard_templates_is_default'), table_name='dashboard_templates')
    op.alter_column('dashboards', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    bind = op.get_bind()
    fks = sa_inspect(bind).get_foreign_keys('dashboards')
    fk_company = next((f['name'] for f in fks if 'company_id' in f.get('constrained_columns', [])), None)
    if fk_company:
        op.drop_constraint(fk_company, 'dashboards', type_='foreignkey')
    op.drop_index(op.f('uq_dashboards_company_id'), table_name='dashboards')
    op.drop_index(op.f('ix_dashboards_company_id'), table_name='dashboards')
    op.create_index(op.f('ix_dashboards_company_id'), 'dashboards', ['company_id'], unique=True)
    if fk_company:
        op.create_foreign_key(None, 'dashboards', 'companies', ['company_id'], ['id'], ondelete='CASCADE')
    op.alter_column('evidences', 'create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('messagens', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('sub_user_requests', 'request_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    # ### end Alembic commands ###


def _index_exists_fkguard(conn, index_name: str, table_name: str) -> bool:
    return (
        conn.execute(
            _sa_text(
                "SELECT COUNT(*) FROM information_schema.statistics "
                "WHERE table_schema = DATABASE() "
                "AND table_name = :tbl AND index_name = :idx"
            ),
            {"tbl": table_name, "idx": index_name},
        ).scalar()
        or 0
    ) > 0


def _index_backs_foreign_key(conn, index_name: str, table_name: str) -> bool:
    """True se alguma FOREIGN KEY desta tabela depende deste índice."""
    return (
        conn.execute(
            _sa_text(
                "SELECT COUNT(*) "
                "FROM information_schema.key_column_usage kcu "
                "JOIN information_schema.statistics s "
                "  ON s.table_schema = kcu.table_schema "
                " AND s.table_name   = kcu.table_name "
                " AND s.column_name  = kcu.column_name "
                "WHERE kcu.table_schema = DATABASE() "
                "  AND kcu.table_name = :tbl "
                "  AND kcu.referenced_table_name IS NOT NULL "
                "  AND s.index_name = :idx"
            ),
            {"tbl": table_name, "idx": index_name},
        ).scalar()
        or 0
    ) > 0


def _drop_index_if_safe(index_name: str, table_name: str) -> None:
    """
    Remove o índice só se ele existir e nenhuma FK depender dele.

    O MySQL recusa `DROP INDEX` sobre um índice que sustenta uma FOREIGN
    KEY:

        (1553, "Cannot drop index '...': needed in a foreign key
                constraint")

    Quando a tabela inteira é removida logo em seguida, ou quando a
    coluna é removida, o índice vai junto — não há o que fazer aqui.
    Descoberto na primeira execução real do job `migrations` do CI
    (2026-08-26): a suíte usa `Base.metadata.create_all` e o SQLite não
    impõe a mesma restrição, então nenhum teste local alcançava isto.
    """
    conn = op.get_bind()
    if not _index_exists_fkguard(conn, index_name, table_name):
        return
    if _index_backs_foreign_key(conn, index_name, table_name):
        return
    op.drop_index(index_name, table_name=table_name)


def _create_index_if_absent(index_name: str, table_name: str, columns, **kw) -> None:
    """
    Cria o índice só se ele ainda não existir.

    Par simétrico de `_drop_index_if_safe`: quando a remoção é pulada
    porque uma FOREIGN KEY depende do índice, a recriação correspondente
    encontraria o índice já lá e falharia com

        (1061, "Duplicate key name '...'")

    Sem as duas guardas, `alembic downgrade base` quebra de um jeito ou
    de outro.
    """
    conn = op.get_bind()
    if _index_exists_fkguard(conn, index_name, table_name):
        return
    op.create_index(index_name, table_name, columns, **kw)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('sub_user_requests', 'request_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('messagens', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('evidences', 'create_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    _drop_index_if_safe("ix_dashboards_company_id", "dashboards")
    _create_index_if_absent("ix_dashboards_company_id", "dashboards", ['company_id'], unique=False)
    _create_index_if_absent("uq_dashboards_company_id", "dashboards", ['company_id'], unique=True)
    op.alter_column('dashboards', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    _create_index_if_absent("ix_dashboard_templates_is_default", "dashboard_templates", ['is_default'], unique=False)
    op.alter_column('dashboard_templates', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('dashboard_templates', 'is_default',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    _create_index_if_absent("ix_dashboard_template_cards_tag", "dashboard_template_cards", ['tag'], unique=False)
    op.alter_column('dashboard_template_cards', 'sort_order',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    _drop_index_if_safe("ix_dashboard_cards_status", "dashboard_cards")
    _drop_index_if_safe("ix_dashboard_cards_control_code", "dashboard_cards")
    op.alter_column('dashboard_cards', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('dashboard_cards', 'sort_order',
               existing_type=mysql.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.drop_column('dashboard_cards', 'status')
    op.drop_column('dashboard_cards', 'control_code')
    op.alter_column('dashboard_card_notes', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    _create_index_if_absent("ix_dashboard_card_messages_message_type", "dashboard_card_messages", ['message_type'], unique=False)
    _create_index_if_absent("ix_dashboard_card_messages_author_user_id", "dashboard_card_messages", ['author_user_id'], unique=False)
    op.alter_column('dashboard_card_messages', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    _create_index_if_absent("ix_dashboard_card_history_entries_actor_user_id", "dashboard_card_history_entries", ['actor_user_id'], unique=False)
    op.alter_column('dashboard_card_history_entries', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.add_column('dashboard_card_checklist_items', sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('dashboard_card_checklist_items', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('dashboard_card_checklist_items', 'done',
               existing_type=mysql.TINYINT(display_width=1),
               server_default=sa.text("'0'"),
               existing_nullable=False)
    op.drop_column('dashboard_card_checklist_items', 'iid')
    _drop_index_if_safe("ix_companies_phone", "companies")
    bind = op.get_bind()
    fks = sa_inspect(bind).get_foreign_keys('companies')
    fk_name = next(
        (fk['name'] for fk in fks if 'principal_user_id' in fk.get('constrained_columns', [])),
        None
    )
    if fk_name:
        op.drop_constraint(fk_name, 'companies', type_='foreignkey')
    _drop_index_if_safe("ix_companies_principal_user_id", "companies")
    _create_index_if_absent("ix_companies_principal_user_id", "companies", ['principal_user_id'], unique=False)
    _drop_index_if_safe("ix_companies_name", "companies")
    _create_index_if_absent("ix_companies_name", "companies", ['name'], unique=False)
    _drop_index_if_safe("ix_companies_email", "companies")
    _create_index_if_absent("ix_companies_email", "companies", ['email'], unique=False)
    _create_index_if_absent("uq_companies_principal_user_id", "companies", ['principal_user_id'], unique=True)
    _create_index_if_absent("uq_companies_name", "companies", ['name'], unique=True)
    _create_index_if_absent("uq_companies_email", "companies", ['email'], unique=True)
    op.create_foreign_key(
        None, 'companies', 'users',
        ['principal_user_id'], ['id'],
        ondelete='RESTRICT'
    )
    op.alter_column('companies', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('(now())'),
               existing_nullable=False)
    op.alter_column('companies', 'phone',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=160),
               nullable=True)
    op.alter_column('checklist_item_state', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('audits', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    op.alter_column('audit_controls', 'created_at',
               existing_type=mysql.DATETIME(),
               server_default=sa.text('CURRENT_TIMESTAMP'),
               existing_nullable=False)
    # ### end Alembic commands ###

